#!/usr/bin/env python3
"""Generate the replication and experiment catalogs from replications.toml.

Single source of truth: ``replications.toml`` at the repo root.
This renders grouped, year-sorted tables into:

  - README.md / README.ja.md  (between the catalog BEGIN/END markers)
  - docs/replications*.md / docs/experiments*.md  (whole files, generator-owned)

USAGE:

    python3 tools/gen_catalog.py            # write/update all target files
    python3 tools/gen_catalog.py --check    # exit 1 if any target is out of date

Zero external dependencies: uses stdlib tomllib (Python 3.11+).
The generator is idempotent: running it twice produces no diff.
"""

from __future__ import annotations

import argparse
import re
import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
TOML_PATH = REPO_ROOT / "replications.toml"

GITHUB_BASE = "https://github.com/akitenkrad"

BEGIN_MARKER = (
    "<!-- BEGIN:replications (auto-generated by tools/gen_catalog.py "
    "— edit replications.toml then re-run) -->"
)
END_MARKER = "<!-- END:replications -->"

EXPERIMENT_BEGIN_MARKER = (
    "<!-- BEGIN:experiments (auto-generated by tools/gen_catalog.py "
    "— edit replications.toml then re-run) -->"
)
EXPERIMENT_END_MARKER = "<!-- END:experiments -->"

# Group ordering and labels.
GROUP_ORDER = ["classic-abm", "llm-social", "game-ai"]
GROUP_LABELS = {
    "classic-abm": {
        "en": "Classic agent-based models",
        "ja": "古典的エージェントベースモデル",
    },
    "llm-social": {
        "en": "LLM-based social simulation",
        "ja": "LLM ベースの社会シミュレーション",
    },
    "game-ai": {
        "en": "Game AI / other",
        "ja": "ゲーム AI・その他",
    },
}

# LLM domain subsection ordering and labels.
DOMAIN_ORDER = ["opinion-norms", "economy", "competition-conflict", "platform-scale", "cognitive-bias-probe"]
DOMAIN_LABELS = {
    "opinion-norms": {
        "en": "Opinion, norms & collective behavior",
        "ja": "意見・規範・集合行動",
    },
    "economy": {
        "en": "Economy, markets & resources",
        "ja": "経済・市場・資源",
    },
    "competition-conflict": {
        "en": "Competition & conflict",
        "ja": "競争・紛争",
    },
    "platform-scale": {
        "en": "Platforms & large-scale simulators",
        "ja": "基盤・大規模シミュレータ",
    },
    "cognitive-bias-probe": {
        "en": "Cognitive biases & behavioral evaluation",
        "ja": "認知バイアス・行動評価",
    },
}

TABLE_HEADER = {
    "en": ("| Year | Paper | Theme | Repo |", "|------|-------|-------|------|"),
    "ja": ("| 年 | 論文 | テーマ | リポジトリ |", "|----|------|--------|------------|"),
}

EXPERIMENT_TABLE_HEADER = {
    "en": ("| Year | Experiment | Theme | Repo |", "|------|------------|-------|------|"),
    "ja": ("| 年 | 実験 | テーマ | リポジトリ |", "|----|------|--------|------------|"),
}


def load_catalog() -> tuple[list[dict], list[dict]]:
    with open(TOML_PATH, "rb") as f:
        data = tomllib.load(f)
    return data.get("replication", []), data.get("experiment", [])


# Keys every [[replication]] entry must define for the catalog to render.
REQUIRED_KEYS = ("key", "repo", "author", "year", "title", "paradigm", "theme_en", "theme_ja")
EXPERIMENT_REQUIRED_KEYS = ("key", "repo", "year", "title", "theme_en", "theme_ja")
EXPERIMENT_KEY_RE = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*$")


def validate_replications(reps: list[dict]) -> None:
    """Fail fast with an actionable message if replications.toml uses an
    unknown paradigm/domain or omits a required field.

    The renderers index closed dicts keyed by `paradigm` (GROUP_ORDER) and,
    for llm-social, by `domain` (DOMAIN_ORDER). Without this check a typo or a
    new category surfaces only as a bare ``KeyError`` stack trace deep in
    rendering. Here we collect every problem and explain how to fix it.
    """
    errors: list[str] = []
    for i, rep in enumerate(reps):
        ident = rep.get("key") or rep.get("repo") or f"entry #{i + 1}"
        for k in REQUIRED_KEYS:
            if k not in rep:
                errors.append(f"[{ident}] missing required field '{k}'")
        paradigm = rep.get("paradigm")
        if paradigm is not None and paradigm not in GROUP_ORDER:
            errors.append(
                f"[{ident}] unknown paradigm '{paradigm}'. "
                f"Allowed: {', '.join(GROUP_ORDER)}. "
                f"Add a new paradigm to GROUP_ORDER/GROUP_LABELS in tools/gen_catalog.py, "
                f"or use an existing one."
            )
        # domain only drives sub-grouping for llm-social; ignored elsewhere.
        if paradigm == "llm-social":
            domain = rep.get("domain")
            if domain not in DOMAIN_ORDER:
                errors.append(
                    f"[{ident}] unknown domain '{domain}' for paradigm 'llm-social'. "
                    f"Allowed: {', '.join(DOMAIN_ORDER)}. "
                    f"Add a new domain to DOMAIN_ORDER/DOMAIN_LABELS in tools/gen_catalog.py, "
                    f"or use an existing one."
                )
    if errors:
        print("replications.toml validation failed:", file=sys.stderr)
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        raise SystemExit(2)


def validate_experiments(experiments: list[dict], reps: list[dict]) -> None:
    """Validate required experiment metadata and key uniqueness."""
    errors: list[str] = []
    replication_keys = {rep.get("key") for rep in reps if rep.get("key") is not None}
    seen: set[str] = set()

    for i, experiment in enumerate(experiments):
        key = experiment.get("key")
        ident = key or experiment.get("repo") or f"entry #{i + 1}"

        for field in EXPERIMENT_REQUIRED_KEYS:
            if field not in experiment:
                errors.append(f"[{ident}] missing required field '{field}'")

        if key is not None:
            if not isinstance(key, str) or EXPERIMENT_KEY_RE.fullmatch(key) is None:
                errors.append(
                    f"[{ident}] invalid experiment key {key!r}. "
                    "Expected lowercase kebab-case matching "
                    f"{EXPERIMENT_KEY_RE.pattern}."
                )
            if isinstance(key, str):
                if key in seen:
                    errors.append(f"[{ident}] duplicate experiment key '{key}'")
                else:
                    seen.add(key)
                if key in replication_keys:
                    errors.append(f"[{ident}] experiment key '{key}' collides with a replication key")

        if "year" in experiment and type(experiment["year"]) is not int:
            errors.append(
                f"[{ident}] field 'year' must be an integer, "
                f"got {type(experiment['year']).__name__}"
            )

    if errors:
        print("replications.toml validation failed:", file=sys.stderr)
        for error in errors:
            print(f"  - {error}", file=sys.stderr)
        raise SystemExit(2)


def year_cell(rep: dict) -> str:
    return rep.get("year_display") or str(rep["year"])


def paper_cell(rep: dict) -> str:
    return f'{rep["author"]}, "{rep["title"]}"'


def theme_cell(rep: dict, lang: str) -> str:
    return rep["theme_en"] if lang == "en" else rep["theme_ja"]


def repo_cell(rep: dict) -> str:
    return f'[{rep["key"]}]({GITHUB_BASE}/{rep["repo"]})'


def render_row(rep: dict, lang: str) -> str:
    cells = [year_cell(rep), paper_cell(rep), theme_cell(rep, lang), repo_cell(rep)]
    return "| " + " | ".join(cells) + " |"


def render_table(reps: list[dict], lang: str) -> list[str]:
    header, sep = TABLE_HEADER[lang]
    lines = [header, sep]
    for rep in sorted(reps, key=lambda r: r["year"]):
        lines.append(render_row(rep, lang))
    return lines


def render_experiment_row(experiment: dict, lang: str) -> str:
    theme = experiment["theme_en"] if lang == "en" else experiment["theme_ja"]
    cells = [
        str(experiment["year"]),
        experiment["title"],
        theme,
        repo_cell(experiment),
    ]
    return "| " + " | ".join(cells) + " |"


def render_experiments_table(experiments: list[dict], lang: str) -> list[str]:
    header, sep = EXPERIMENT_TABLE_HEADER[lang]
    lines = [header, sep]
    for experiment in sorted(experiments, key=lambda item: (item["year"], item["key"])):
        lines.append(render_experiment_row(experiment, lang))
    return lines


def group_reps(reps: list[dict]) -> dict[str, list[dict]]:
    groups: dict[str, list[dict]] = {g: [] for g in GROUP_ORDER}
    for rep in reps:
        groups[rep["paradigm"]].append(rep)
    return groups


def render_grouped_tables(reps: list[dict], lang: str, heading_level: int) -> list[str]:
    """Render all group headings + tables. heading_level is the '#' count for groups."""
    h = "#" * heading_level
    sub_h = "#" * (heading_level + 1)
    groups = group_reps(reps)
    lines: list[str] = []

    for paradigm in GROUP_ORDER:
        group_reps_list = groups[paradigm]
        if not group_reps_list:
            continue
        lines.append("")
        lines.append(f"{h} {GROUP_LABELS[paradigm][lang]}")
        lines.append("")

        if paradigm == "llm-social":
            by_domain: dict[str, list[dict]] = {d: [] for d in DOMAIN_ORDER}
            for rep in group_reps_list:
                by_domain[rep["domain"]].append(rep)
            domains = [d for d in DOMAIN_ORDER if by_domain[d]]
            for i, domain in enumerate(domains):
                lines.append(f"{sub_h} {DOMAIN_LABELS[domain][lang]}")
                lines.append("")
                lines.extend(render_table(by_domain[domain], lang))
                if i < len(domains) - 1:
                    lines.append("")
        else:
            lines.extend(render_table(group_reps_list, lang))

    return lines


def category_counts(reps: list[dict]) -> dict[str, int]:
    groups = group_reps(reps)
    return {g: len(groups[g]) for g in GROUP_ORDER}


def used_group_count(reps: list[dict]) -> int:
    return sum(1 for g in GROUP_ORDER if group_reps(reps)[g])


# --- README block --------------------------------------------------------------

def render_readme_block(reps: list[dict], lang: str) -> str:
    total = len(reps)
    n_cat = used_group_count(reps)
    if lang == "en":
        summary = (
            f"{total} replications across {n_cat} categories — see the full catalog "
            f"in [docs/replications.md](docs/replications.md)."
        )
    else:
        summary = (
            f"全 {total} 件の再現実装を {n_cat} カテゴリに分類しています"
            f"．完全なカタログは [docs/replications.ja.md](docs/replications.ja.md) を参照してください．"
        )
    lines = [BEGIN_MARKER, "", summary]
    lines.extend(render_grouped_tables(reps, lang, heading_level=3))
    lines.append("")
    lines.append(END_MARKER)
    return "\n".join(lines)


def splice_readme(content: str, block: str) -> str:
    start = content.find(BEGIN_MARKER)
    end = content.find(END_MARKER)
    if start == -1 or end == -1:
        raise ValueError("BEGIN/END:replications markers not found in README")
    end_full = end + len(END_MARKER)
    return content[:start] + block + content[end_full:]


def render_experiments_readme_block(experiments: list[dict], lang: str) -> str:
    lines = [EXPERIMENT_BEGIN_MARKER]
    if experiments:
        lines.extend(render_experiments_table(experiments, lang))
    else:
        lines.append("No experiments yet." if lang == "en" else "新規実験はまだありません．")
    lines.append(EXPERIMENT_END_MARKER)
    return "\n".join(lines)


def splice_experiments_readme(content: str, block: str) -> str:
    start = content.find(EXPERIMENT_BEGIN_MARKER)
    end = content.find(EXPERIMENT_END_MARKER)
    if start == -1 or end == -1:
        raise ValueError("BEGIN/END:experiments markers not found in README")
    end_full = end + len(EXPERIMENT_END_MARKER)
    return content[:start] + block + content[end_full:]


# --- docs/replications*.md (whole file, generator-owned) ------------------------

def render_docs_file(reps: list[dict], lang: str) -> str:
    counts = category_counts(reps)
    total = len(reps)
    if lang == "en":
        title = "# Replication catalog"
        parts = []
        for g in GROUP_ORDER:
            if counts[g]:
                parts.append(f"{counts[g]} {GROUP_LABELS[g]['en']}")
        intro = (
            f"{total} replication implementations of social-simulation papers, "
            f"grouped by modeling paradigm: " + "; ".join(parts) + "."
        )
        switcher = "**English** | [日本語](replications.ja.md)"
    else:
        title = "# 再現実装カタログ"
        parts = []
        for g in GROUP_ORDER:
            if counts[g]:
                parts.append(f"{GROUP_LABELS[g]['ja']} {counts[g]} 件")
        intro = (
            f"社会シミュレーション系論文の再現実装 全 {total} 件を，"
            f"モデリングパラダイムごとに分類しています："
            + "，".join(parts)
            + "．"
        )
        switcher = "[English](replications.md) | **日本語**"

    lines = [switcher, "", title, "", intro]
    lines.extend(render_grouped_tables(reps, lang, heading_level=2))
    lines.append("")
    return "\n".join(lines)


def render_experiments_docs_file(experiments: list[dict], lang: str) -> str:
    if lang == "en":
        switcher = "**English** | [日本語](experiments.ja.md)"
        title = "# Experiment catalog"
        intro = "Original social-simulation experiments that are not tied to a source paper."
        empty = "No experiments yet."
    else:
        switcher = "[English](experiments.md) | **日本語**"
        title = "# 新規実験カタログ"
        intro = "出典論文を持たない独自の社会シミュレーション実験を掲載しています．"
        empty = "新規実験はまだありません．"

    lines = [switcher, "", title, "", intro, ""]
    if experiments:
        lines.extend(render_experiments_table(experiments, lang))
    else:
        lines.append(empty)
    lines.append("")
    return "\n".join(lines)


# --- target registry ------------------------------------------------------------

def build_targets(reps: list[dict], experiments: list[dict]) -> dict[Path, str]:
    """Return {path: desired_content}. README files are spliced; docs are whole."""
    targets: dict[Path, str] = {}

    for fname, lang in [("README.md", "en"), ("README.ja.md", "ja")]:
        path = REPO_ROOT / fname
        existing = path.read_text(encoding="utf-8")
        block = render_readme_block(reps, lang)
        content = splice_readme(existing, block)
        experiments_block = render_experiments_readme_block(experiments, lang)
        targets[path] = splice_experiments_readme(content, experiments_block)

    for fname, lang in [
        ("docs/replications.md", "en"),
        ("docs/replications.ja.md", "ja"),
    ]:
        path = REPO_ROOT / fname
        targets[path] = render_docs_file(reps, lang)

    for fname, lang in [
        ("docs/experiments.md", "en"),
        ("docs/experiments.ja.md", "ja"),
    ]:
        path = REPO_ROOT / fname
        targets[path] = render_experiments_docs_file(experiments, lang)

    return targets


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if any target file is out of date (do not write)",
    )
    args = parser.parse_args()

    reps, experiments = load_catalog()
    validate_replications(reps)
    validate_experiments(experiments, reps)
    targets = build_targets(reps, experiments)

    if args.check:
        stale = []
        for path, desired in targets.items():
            current = path.read_text(encoding="utf-8") if path.exists() else None
            if current != desired:
                stale.append(path)
        if stale:
            print("Out of date (run `python3 tools/gen_catalog.py` to regenerate):")
            for path in stale:
                print(f"  {path.relative_to(REPO_ROOT)}")
            return 1
        print("All catalog targets are up to date.")
        return 0

    changed = []
    for path, desired in targets.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != desired:
            path.write_text(desired, encoding="utf-8")
            changed.append(path)

    if changed:
        print("Updated:")
        for path in changed:
            print(f"  {path.relative_to(REPO_ROOT)}")
    else:
        print("No changes (already up to date).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
