#!/usr/bin/env python3
"""Generate the replication catalog from replications.toml.

Single source of truth: ``replications.toml`` at the repo root.
This renders grouped, year-sorted tables into:

  - README.md / README.ja.md  (between the BEGIN/END:replications markers)
  - docs/replications.md / docs/replications.ja.md  (whole file, generator-owned)

USAGE:

    python3 tools/gen_catalog.py            # write/update all target files
    python3 tools/gen_catalog.py --check    # exit 1 if any target is out of date

Zero external dependencies: uses stdlib tomllib (Python 3.11+).
The generator is idempotent: running it twice produces no diff.
"""

from __future__ import annotations

import argparse
import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
TOML_PATH = REPO_ROOT / "replications.toml"

GITHUB_BASE = "https://github.com/akitenkrad"

BEGIN_MARKER = (
    "<!-- BEGIN:replications (auto-generated by tools/gen_catalog.py "
    "— edit replications.toml then re-run) -->"
)
END_MARKER = "<!-- END:replications -->"

# Group ordering and labels.
GROUP_ORDER = ["classic-abm", "llm-social", "game-ai"]
GROUP_LABELS = {
    "classic-abm": {
        "en": "Classic agent-based models",
        "ja": "古典的エージェントベースモデル",
    },
    "llm-social": {
        "en": "LLM-based social simulation",
        "ja": "LLM ベースの社会シミュレーション",
    },
    "game-ai": {
        "en": "Game AI / other",
        "ja": "ゲーム AI・その他",
    },
}

# LLM domain subsection ordering and labels.
DOMAIN_ORDER = ["opinion-norms", "economy", "competition-conflict", "platform-scale"]
DOMAIN_LABELS = {
    "opinion-norms": {
        "en": "Opinion, norms & collective behavior",
        "ja": "意見・規範・集合行動",
    },
    "economy": {
        "en": "Economy, markets & resources",
        "ja": "経済・市場・資源",
    },
    "competition-conflict": {
        "en": "Competition & conflict",
        "ja": "競争・紛争",
    },
    "platform-scale": {
        "en": "Platforms & large-scale simulators",
        "ja": "基盤・大規模シミュレータ",
    },
}

TABLE_HEADER = {
    "en": ("| Year | Paper | Theme | Repo |", "|------|-------|-------|------|"),
    "ja": ("| 年 | 論文 | テーマ | リポジトリ |", "|----|------|--------|------------|"),
}


def load_replications() -> list[dict]:
    with open(TOML_PATH, "rb") as f:
        data = tomllib.load(f)
    return data.get("replication", [])


def year_cell(rep: dict) -> str:
    return rep.get("year_display") or str(rep["year"])


def paper_cell(rep: dict) -> str:
    return f'{rep["author"]}, "{rep["title"]}"'


def theme_cell(rep: dict, lang: str) -> str:
    return rep["theme_en"] if lang == "en" else rep["theme_ja"]


def repo_cell(rep: dict) -> str:
    return f'[{rep["key"]}]({GITHUB_BASE}/{rep["repo"]})'


def render_row(rep: dict, lang: str) -> str:
    cells = [year_cell(rep), paper_cell(rep), theme_cell(rep, lang), repo_cell(rep)]
    return "| " + " | ".join(cells) + " |"


def render_table(reps: list[dict], lang: str) -> list[str]:
    header, sep = TABLE_HEADER[lang]
    lines = [header, sep]
    for rep in sorted(reps, key=lambda r: r["year"]):
        lines.append(render_row(rep, lang))
    return lines


def group_reps(reps: list[dict]) -> dict[str, list[dict]]:
    groups: dict[str, list[dict]] = {g: [] for g in GROUP_ORDER}
    for rep in reps:
        groups[rep["paradigm"]].append(rep)
    return groups


def render_grouped_tables(reps: list[dict], lang: str, heading_level: int) -> list[str]:
    """Render all group headings + tables. heading_level is the '#' count for groups."""
    h = "#" * heading_level
    sub_h = "#" * (heading_level + 1)
    groups = group_reps(reps)
    lines: list[str] = []

    for paradigm in GROUP_ORDER:
        group_reps_list = groups[paradigm]
        if not group_reps_list:
            continue
        lines.append("")
        lines.append(f"{h} {GROUP_LABELS[paradigm][lang]}")
        lines.append("")

        if paradigm == "llm-social":
            by_domain: dict[str, list[dict]] = {d: [] for d in DOMAIN_ORDER}
            for rep in group_reps_list:
                by_domain[rep["domain"]].append(rep)
            domains = [d for d in DOMAIN_ORDER if by_domain[d]]
            for i, domain in enumerate(domains):
                lines.append(f"{sub_h} {DOMAIN_LABELS[domain][lang]}")
                lines.append("")
                lines.extend(render_table(by_domain[domain], lang))
                if i < len(domains) - 1:
                    lines.append("")
        else:
            lines.extend(render_table(group_reps_list, lang))

    return lines


def category_counts(reps: list[dict]) -> dict[str, int]:
    groups = group_reps(reps)
    return {g: len(groups[g]) for g in GROUP_ORDER}


def used_group_count(reps: list[dict]) -> int:
    return sum(1 for g in GROUP_ORDER if group_reps(reps)[g])


# --- README block --------------------------------------------------------------

def render_readme_block(reps: list[dict], lang: str) -> str:
    total = len(reps)
    n_cat = used_group_count(reps)
    if lang == "en":
        summary = (
            f"{total} replications across {n_cat} categories — see the full catalog "
            f"in [docs/replications.md](docs/replications.md)."
        )
    else:
        summary = (
            f"全 {total} 件の再現実装を {n_cat} カテゴリに分類しています"
            f"．完全なカタログは [docs/replications.ja.md](docs/replications.ja.md) を参照してください．"
        )
    lines = [BEGIN_MARKER, "", summary]
    lines.extend(render_grouped_tables(reps, lang, heading_level=3))
    lines.append("")
    lines.append(END_MARKER)
    return "\n".join(lines)


def splice_readme(content: str, block: str) -> str:
    start = content.find(BEGIN_MARKER)
    end = content.find(END_MARKER)
    if start == -1 or end == -1:
        raise ValueError("BEGIN/END:replications markers not found in README")
    end_full = end + len(END_MARKER)
    return content[:start] + block + content[end_full:]


# --- docs/replications*.md (whole file, generator-owned) ------------------------

def render_docs_file(reps: list[dict], lang: str) -> str:
    counts = category_counts(reps)
    total = len(reps)
    if lang == "en":
        title = "# Replication catalog"
        parts = []
        for g in GROUP_ORDER:
            if counts[g]:
                parts.append(f"{counts[g]} {GROUP_LABELS[g]['en']}")
        intro = (
            f"{total} replication implementations of social-simulation papers, "
            f"grouped by modeling paradigm: " + "; ".join(parts) + "."
        )
        switcher = "**English** | [日本語](replications.ja.md)"
    else:
        title = "# 再現実装カタログ"
        parts = []
        for g in GROUP_ORDER:
            if counts[g]:
                parts.append(f"{GROUP_LABELS[g]['ja']} {counts[g]} 件")
        intro = (
            f"社会シミュレーション系論文の再現実装 全 {total} 件を，"
            f"モデリングパラダイムごとに分類しています："
            + "，".join(parts)
            + "．"
        )
        switcher = "[English](replications.md) | **日本語**"

    lines = [switcher, "", title, "", intro]
    lines.extend(render_grouped_tables(reps, lang, heading_level=2))
    lines.append("")
    return "\n".join(lines)


# --- target registry ------------------------------------------------------------

def build_targets(reps: list[dict]) -> dict[Path, str]:
    """Return {path: desired_content}. README files are spliced; docs are whole."""
    targets: dict[Path, str] = {}

    for fname, lang in [("README.md", "en"), ("README.ja.md", "ja")]:
        path = REPO_ROOT / fname
        existing = path.read_text(encoding="utf-8")
        block = render_readme_block(reps, lang)
        targets[path] = splice_readme(existing, block)

    for fname, lang in [
        ("docs/replications.md", "en"),
        ("docs/replications.ja.md", "ja"),
    ]:
        path = REPO_ROOT / fname
        targets[path] = render_docs_file(reps, lang)

    return targets


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if any target file is out of date (do not write)",
    )
    args = parser.parse_args()

    reps = load_replications()
    targets = build_targets(reps)

    if args.check:
        stale = []
        for path, desired in targets.items():
            current = path.read_text(encoding="utf-8") if path.exists() else None
            if current != desired:
                stale.append(path)
        if stale:
            print("Out of date (run `python3 tools/gen_catalog.py` to regenerate):")
            for path in stale:
                print(f"  {path.relative_to(REPO_ROOT)}")
            return 1
        print("All catalog targets are up to date.")
        return 0

    changed = []
    for path, desired in targets.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != desired:
            path.write_text(desired, encoding="utf-8")
            changed.append(path)

    if changed:
        print("Updated:")
        for path in changed:
            print(f"  {path.relative_to(REPO_ROOT)}")
    else:
        print("No changes (already up to date).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
